create database Inventory_Management_System;
USE Inventory_Management_System;
create table EMPLOYEE(
	username VARCHAR(50),
	pwd VARCHAR(50),
	age INT,
	role VARCHAR(50)
)

INSERT INTO EMPLOYEE VALUES('HOANG LONG', 'HUHU', 20, 'ADMIN');
INSERT INTO EMPLOYEE VALUES('XUANSON', 'HIHIU', 20, 'ADMIN');
INSERT INTO EMPLOYEE VALUES('THETIEM', 'HAHA', 20, 'ADMIN');
INSERT INTO EMPLOYEE VALUES('DUONGTUNG', 'HOHO', 20, 'ADMIN');
