USE Inventory_Management_System;

--- CREATE TABLE

CREATE TABLE ACCOUNT(
	-- Table lưu trữ thông tin account của user
	id_account VARCHAR(100),
	username VARCHAR(100),
	pwd VARCHAR(100),
	account_role INT

	CONSTRAINT PK_ACCOUNT PRIMARY KEY(id_account)
)

CREATE TABLE USERS(
	-- Table lưu trữ thông tin user

	id_user VARCHAR(100),
	id_account VARCHAR(100),
	fullname VARCHAR(100),
	age DATE,
	email VARCHAR(100)

	CONSTRAINT PK_USER PRIMARY KEY(id_user),
	CONSTRAINT FK_USER_ACCOUNT FOREIGN KEY(id_account) REFERENCES ACCOUNT(id_account) ON DELETE CASCADE
)


CREATE TABLE CUSTOMER_INFO(
	-- Table lưu trữ thông tin khách hàng

	id_cus VARCHAR(100),
	name_cus VARCHAR(100),
	phone_cus VARCHAR(100),
	address_cus VARCHAR(100)

	CONSTRAINT PK_CUSTOMER_INFO PRIMARY KEY(id_cus)
)

CREATE TABLE ORDERS(
	-- Table lưu trữ thông tin đơn hàng

	id_ord VARCHAR(100),
	id_user VARCHAR(100),
	id_cus VARCHAR(100),
	type_ord VARCHAR(100),
	date_ord DATE

	CONSTRAINT PK_ORDER PRIMARY KEY(id_ord),
	CONSTRAINT FK_ORDER_USER FOREIGN KEY(id_user) REFERENCES USERS(id_user) ON DELETE SET NULL,
	CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY(id_cus) REFERENCES CUSTOMER_INFO(id_cus) ON DELETE SET NULL
)

CREATE TABLE ORD_STATE(
	-- Table lưu trữ trạng thái đơn hàng
	id_ordst VARCHAR(100),
	id_ord VARCHAR(100),
	admin_state VARCHAR(100),
	warehouse_mng_state VARCHAR(100),
	date_2state_return DATE

	CONSTRAINT PK_ORD_STATE PRIMARY KEY(id_ordst, id_ord),
	CONSTRAINT FK_ORDST_ORDER FOREIGN KEY(id_ord) REFERENCES ORDERS(id_ord) ON DELETE CASCADE
)

CREATE TABLE PRODUCTION(
	-- Table lưu trữ thông tin sản phẩm

	id_prod VARCHAR(100),
	name_prod VARCHAR(100),
	type_prod VARCHAR(100),
	price INT,
	num_exist INT,
	state_prod INT

	CONSTRAINT PK_PRODUCTION PRIMARY KEY(id_prod)
)

CREATE TABLE ORD_DETAIL(
	-- Table lưu trữ thông tin đơn hàng

	id_ord VARCHAR(100),
	id_prod VARCHAR(100),
	num_ord INT

	CONSTRAINT PK_ORD_DETAIL PRIMARY KEY(id_ord, id_prod),
	CONSTRAINT FK_ORDDT_ORDER FOREIGN KEY(id_ord) REFERENCES ORDERS(id_ord) ON DELETE CASCADE,
	CONSTRAINT FK_ORDDT_PRODUCTION FOREIGN KEY(id_prod) REFERENCES PRODUCTION(id_prod)
)

-- Dưới đây là những lệnh hỗ trợ
ALTER TABLE USERS NOCHECK CONSTRAINT ALL;
ALTER TABLE ACCOUNT NOCHECK CONSTRAINT ALL;
ALTER TABLE ORDERS NOCHECK CONSTRAINT ALL;
ALTER TABLE ORD_STATE NOCHECK CONSTRAINT ALL;
ALTER TABLE CUSTOMER_INFO NOCHECK CONSTRAINT ALL;
ALTER TABLE PRODUCTION NOCHECK CONSTRAINT ALL;
ALTER TABLE ORD_DETAIL NOCHECK CONSTRAINT ALL;

DROP TABLE USERS;
DROP TABLE ACCOUNT;
DROP TABLE ORDERS;
DROP TABLE ORD_STATE;
DROP TABLE CUSTOMER_INFO;
DROP TABLE PRODUCTION;
DROP TABLE ORD_DETAIL;

SET DATEFORMAT dmy;
-- INSERT TABLE DEMO

-- Phần insert demo để có thể sign in vào app
-- ACCOUNT
INSERT INTO ACCOUNT VALUES('ACCOUNT01', 'hoanglong', '123long', 1);
INSERT INTO ACCOUNT VALUES('ACCOUNT02', 'thetiem', '123tiem', 2);
INSERT INTO ACCOUNT VALUES('ACCOUNT03', 'duongtung', '123tung', 3);
INSERT INTO ACCOUNT VALUES('ACCOUNT04', 'xuanson', '123son', 1);

-- USERS
INSERT INTO USERS VALUES('USER01', (SELECT id_account FROM ACCOUNT WHERE id_account='ACCOUNT01'), 'Nguyen Hoang Long', '2020-12-17', 'hoanglong@gmail.com');
INSERT INTO USERS VALUES('USER02', (SELECT id_account FROM ACCOUNT WHERE id_account='ACCOUNT02'), 'Le The Tiem', '2020-12-18', 'thetiem@gmail.com');
INSERT INTO USERS VALUES('USER03', (SELECT id_account FROM ACCOUNT WHERE id_account='ACCOUNT03'), 'Nguyen Duong Tung', '2020-12-19', 'duongtung@gmail.com');
INSERT INTO USERS VALUES('USER04', (SELECT id_account FROM ACCOUNT WHERE id_account='ACCOUNT04'), 'Chu Xuan Son', '2020-12-20', 'xuanson@gmail.com');

-- PRODUCTION
INSERT INTO PRODUCTION VALUES('PRODUCTION01', 'Dell Vostro 1230', 'DELL', 100000000, 50, 1);
INSERT INTO PRODUCTION VALUES('PRODUCTION02', 'Thinkpad 1230', 'Asus', 300000000, 20, 1);
INSERT INTO PRODUCTION VALUES('PRODUCTION03', 'HP 1530"', 'HP', 900000000, 80, 1);
INSERT INTO PRODUCTION VALUES('PRODUCTION04', 'Mac Retina 1230', 'Macbook', 200000000, 20, 1);
INSERT INTO PRODUCTION VALUES('PRODUCTION05', 'Dell 1830', 'DELL', 400000000, 20, 1);

-- ORDERS

-- Phần SELECT
-- USERS
SELECT *
FROM USERS;

-- ACCOUNT
SELECT *
FROM ACCOUNT;

-- PRODUCTION
SELECT *
FROM PRODUCTION;

-- ORDERS
SELECT *
FROM ORDERS;

-- ORD_STATE
SELECT *
FROM ORD_STATE;

-- CUSTOMER_INFO
SELECT *
FROM CUSTOMER_INFO;

-- ORD_DETAIL
SELECT *
FROM ORD_DETAIL;
